services:
    db:
        image: postgres:15
        platform: linux/amd64 # Or linux/arm64 if on ARM
        environment:
            POSTGRES_DB: "squidfrost"
            POSTGRES_PASSWORD: postgres
        ports:
            - "5432:5432"
